# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

### Import NumPy as its abbreviation 'np'

In [98]:
import numpy as np

### Create a 1-dimensional NumPy array using np.array() 

In [99]:
arr1D = np.array([1,2,3,4])

### Create a 2-dimensional NumPy array using np.array() 

In [100]:
arr2D = np.array([[1,2,3,4],[5,6,7,8]])

### Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type) 

In [101]:
arr1D.shape, arr1D.ndim, arr1D.dtype, arr1D.size, type(arr1D)

((4,), 1, dtype('int32'), 4, numpy.ndarray)

### Attributes of 2-dimensional array

In [102]:
arr2D.shape, arr2D.ndim, arr2D.dtype, arr2D.size, type(arr2D)

((2, 4), 2, dtype('int32'), 8, numpy.ndarray)

### Create an array of shape (5, 5) with only ones 

In [103]:
ones = np.ones((5,5))

### Create an array of shape (3, 3, 5) with only zeros

In [104]:
zeros = np.zeros((3, 3, 5))

### Create a random array with numbers between 0 and 10 of size (7, 2)

In [105]:
randomArray = np.random.randint(10, size=(7, 2))

### Create a random array of floats between 0 & 1 of shape (3, 5)

In [106]:
random_Array = np.random.random((3, 5))

### Create an array of normally distributed random numbers

In [107]:
NormalDis = np.random.normal(0,10,10)
NormalDis

array([-15.50663431,   0.68562975, -10.62303714,   4.73592431,
        -9.19424234,  15.49934405,  -7.83253292,  -3.22061516,
         8.13517217, -12.30864316])

### Set the random seed to 42
### Create a random array of numbers between 0 & 10 of size (4, 6)

In [108]:
np.random.seed(42)
RandArray = np.random.randint(10, size=(4, 6))
RandArray

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

### Copy the code from the cell above and run it again

In [109]:
np.random.seed(42)
RandArray = np.random.randint(10, size=(4, 6))
RandArray

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

### Find the 0'th index of the latest array you created

In [110]:
RandArray[0]

array([6, 3, 7, 4, 6, 9])

### Get the first 2 rows of latest array you created

In [111]:
RandArray[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

### Get the first 2 values of the first 2 rows of the latest array

In [112]:
RandArray[:2,:2]

array([[6, 3],
       [2, 6]])

### Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables

In [113]:
Array = np.random.randint(10, size=(3,5))
ones = np.ones((3,5))
Array

array([[8, 0, 9, 2, 6],
       [3, 8, 2, 4, 2],
       [6, 4, 8, 6, 1]])

### Add the two arrays together

In [114]:
Array + ones

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

### Create another array of ones of shape (5, 3)

In [115]:
Ones = np.ones((5,3))

### Try add the array of ones and the other most recent array together # You can anticipate an error

In [116]:
Array + Ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

### Do the same operation you just did but this time with a transpose on one array

In [ ]:
Array.T + Ones

### Take the latest array to the power of 2 using the python way

In [ ]:
Array ** 2

### Do the same thing with numpy way

In [ ]:
np.power(Array, 2)

### Find the mean, min, max, standard deviation, variance of the latest array using np.mean()

In [ ]:
np.mean(Array), np.max(Array), np.min(Array), np.std(Array), np.var(Array)

### Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)

In [ ]:
a1 = np.random.randint(10, size = (3,3))
a2 = np.random.randint(10, size = (3,2))

### Perform a dot product on the two newest arrays you created

In [ ]:
np.dot(a1, a2)

### Create two arrays of random integers between 0 to 10 both of size (4, 3)

In [ ]:
b1 = np.random.randint(10, size = (4,3))
b2 = np.random.randint(10, size = (4,3))

### Perform a hadamard product on the two newest arrays you created

In [ ]:
b1 * b2

### Perform a dot product on the two newest arrays you created # Error anticipated

In [ ]:
np.dot(b1, b2)

### Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both

In [ ]:
np.dot(b1, b2.T)

### Create two arrays of random integers between 0 & 10 of the same shape and save them to variables

In [ ]:
a1 = np.random.randint(10, size = (3,5))
a2 = np.random.randint(10, size = (3,5))

### Compare the two arrays with '>', '<=' and '=='

In [ ]:
 a1  

In [ ]:
a2

In [ ]:
a1 > a2

In [ ]:
a1 <= a2

In [ ]:
a1 == a2

In [ ]:
a1

### Sort one of the arrays you just created in ascending order

In [117]:
np.sort(a1)

array([[2, 3, 5, 6, 8],
       [0, 2, 4, 7, 8],
       [5, 7, 7, 8, 9]])

### Sort the indexes of one of the arrays you just created

In [118]:
np.argsort(a1)

array([[2, 0, 4, 3, 1],
       [3, 4, 2, 0, 1],
       [2, 1, 3, 4, 0]], dtype=int64)

### Find the index with the maximum value in one of the arrays you've created

In [119]:
np.argmax(a1)

10

### Create an array with 10 evenly spaced numbers between 1 and 100

In [120]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

### Find the indexes with the maximum values down the verticial axis of one of the arrays you created

In [121]:
np.argmax(a1,axis=0)

array([2, 0, 2, 2, 2], dtype=int64)

### Find the indexes with the minimum values across the horizontal axis of one of the arrays you created

In [122]:
np.argmin(a1,axis=1)

array([2, 3, 2], dtype=int64)